[server]
root_url = https://grafana.meetjestad.net

[users]
# Do not allow signup for normal accounts
allow_sign_up = false
# But auto assign a role to users created for oauth logins
auto_assign_org_role = Editor

[auth]
# On signout redirect to the non-webauth host, so when you are auto-logged in
# on the internal network and select logout, you actually get a login prompt
# instead of being logged in again automatically
signout_redirect_url = https://grafana.meetjestad.net

[auth.generic_oauth]
# https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#team-synchronization
name = Plan B Nextcloud
icon = signin
enabled = true
#client_id = Bx7aH7BsCAjDjhqr5evAh01rogGtzfiyQ87APyNPNdRGYijUgtTV2fFFMROwovPN
#client_secret = I3WNOiwHrU2YtfZb8FLjVCct6WmkrTuornh9tKcVRMvVDW45jsnsMzMF472zQLlB
scopes = openid profile email
allow_sign_up = true
use_pkce = true
auth_url = https://nextcloud.planb.coop/apps/oidc/authorize
token_url = https://nextcloud.planb.coop/apps/oidc/token
api_url = https://nextcloud.planb.coop/apps/oidc/userinfo
# Nextcloud does not return meaningful roles, so just assign the default rule
# on user creation and them manage roles manually within Grafana.
# We *could* have Nextcloud return group names and use a complex JMESPath
# queries to map specific group names to role names, manual management is
# easier for now.
oauth_skip_org_role_update_sync = true
# Point to the Nextcloud username (defaults are fine for email and name)
login_attribute_path = preferred_username


# This allows creating very limited sharing links, which cannot even change the
# timespan, so this is not super useful. However, anonymous access cannot be
# limited to specific dashboards (Viewer role is the minimum, which gives access
# to arbitrary queries). This also applies to proxy auth. Public dashboards use a
# different way to access datasources, which *is* limited to queries defined in
# the public dashboard. Hopefully this will be genaralized to anonymous/proxy
# users in the future too. See:
# https://github.com/grafana/grafana/issues/6180#issuecomment-1416910375
# https://github.com/grafana/grafana/issues/19172#issuecomment-1416914682
[feature_toggles]
publicDashboards = true

# This allows anonymous access to all data
[auth.anonymous]
enabled = true
org_role = Viewer

[log]
level = debug

[panels]
# This allows using iframes in Text/HTML panels
disable_sanitize_html = true
