# This container sets up ipv6 NAT, so containers can be reached on ipv6 and
# reach out using ipv6. Docker does not support this (yet), but will probably
# do so in a future version.
# See:
#  - https://github.com/moby/moby/pull/41622
#  - https://github.com/moby/moby/issues/41754
---
version: '2'
services:
  ipv6nat:
    image: robbertkl/ipv6nat:0.4.4
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add:
     - NET_ADMIN
    network_mode: host

# vim: set sw=2 sts=2 et:
