---
version: '2.4'
services:
  portainer:
    image: portainer/portainer-ce:2.0.1
    environment:
      VIRTUAL_HOST: portainer.planb.coop
      LETSENCRYPT_HOST: portainer.planb.coop
      VIRTUAL_PORT: 9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock 
     - data:/data

volumes:
  data:

networks:
  default:
    external:
      name: nginx-proxy
